# Generated by Django 4.1.7 on 2023-04-28 14:40

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_products_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.getFileName),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
