# Generated by Django 4.1.7 on 2023-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
