# Generated by Django 4.1.7 on 2023-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_images_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_image',
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
