# Generated by Django 4.1.7 on 2023-04-28 15:37

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_products_product_image_alter_images_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.getFileName),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
