# Generated by Django 4.1.7 on 2023-05-03 05:21

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_user_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Accounts.models.getFileName)),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_image',
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ManyToManyField(blank=True, to='Accounts.image'),
        ),
    ]
